[app]
title = AnkiTXT
package.name = ankitxt
package.domain = org.ankitxt
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 1.0.0
requirements = python3,kivy
orientation = portrait
fullscreen = 0
android.permissions = READ_EXTERNAL_STORAGE,WRITE_EXTERNAL_STORAGE
android.api = 31
android.minapi = 21
android.accept_sdk_license = True
p4a.bootstrap = sdl2
android.archs = arm64-v8a, armeabi-v7a
android.ndk = 25b
android.allow_backup = False
icon.filename = icon.png
